### PR TITLE
Collapsible Chapters

### PR DESCRIPTION
**Pull request by colevandersWands**
Hello Shawnr.  

I just found your book today and think it's pretty awesome.   As a token of good faith here's a pull request that will make your chapters collapse so you don't have to scroll so much on the index.

I'm currently working on open-sourcing the curriculum I use in my developer classes.  What I'm missing is something exactly like what you have here: a thorough introduction to the javascript language and best practices for total beginners.  Would you be interested in incorporating your gitbook as the first step in my curriculum?  Either as a fork or a direct link to your hosting.

You can check out what I'm putting together here:  https://elewa-academy.github.io

Best,

Evan

### CODE REVIEW

**Comment by colevandersWands** [comment]
PS.  J'aime bien L'Ecrivain

**Comment by colevandersWands** [comment]
PPS. The embedded quizzes are crux.  I hadn't found a good way to do that yet, we were planning on linking to google forms

**Comment by shawnr** [comment]
@colevandersWands Thanks so much for the PR! I will happily take this change. Give me a chance to try it out this weekend and I will merge it in quickly.

Thanks for your kind words re: the book and your curriculum. I'd be happy to discuss how to incorporate the book, and you are, of course, free to use it however you'd like.

**Comment by shawnr** [comment]
Thanks so much for this!

**Pull request merged**
